### ISSUE TITLE
All detectors are giving axis out of bounds errors

### ISSUE THREAD

**Issue by AngCamp** [Eden-Kramer-Lab/ripple_detection#3]
Where I supply LFP data as a nd array or as a 1d array all the dectors produce the following error: AxisError: axis 1 is out of bounds for array of dimension 1

**Comment by edeno** [comment]
Hi @AngCamp , could you post the specific error traceback? It seems like the array you are inputting only has one dimension whereas the code requires 2D arrays. You can always add an axis by using np.newaxis.
