### ISSUE TITLE
80-125Hz ripple detection

### ISSUE THREAD

**Issue by smile0227** [Eden-Kramer-Lab/ripple_detection#4]
Dear edeno,
I'm sorry to bother you.
Does this code apply to ripple detection at 80-125Hz?
Looking forward to your reply

Yours,
Xiaoke

**Comment by edeno** [comment]
Hi Xiaoke,

The ripple detectors take in the filtered lfps as input. So if you've filtered your data between 80-125 Hz, then it should work.

**Comment by smile0227** [comment]
Dear edeno,
I am so happy to receive your reply. Thanks for your answer.
I want to apply _**Karlsson_ripple_detector**_ to the magnetoencephalogram of epileptic patients to detect 80-125Hz ripples.
Besides filtering parameters, do you have any good suggestions on setting _**zscore_threshold**_ and _**smoothing_sigma**_?
Moreover, could I ignore the calculation about the _**speed_threshold**_?
I'm looking forward to your earliest reply. 
Yours,
Xiaoke

**Comment by edeno** [comment]
Ah, I see. Well I don't know much about what thresholds would work for human patients. I would look at this paper: https://www.nature.com/articles/s41467-022-33536-x

You can ignore the speed threshold by setting it ones or some value under the current speed threshold.

**Comment by smile0227** [comment]
Dear edeno,
Thank you for your kind proposal,  which is important to me.
Yours,
Xiaoke
