### ISSUE TITLE
Add ripple size metric

### ISSUE THREAD

**Issue by edeno** [Eden-Kramer-Lab/ripple_detection#7]
maximum threshold ( in units of sd) at which the event would still be detected (ie be above for >15ms or whatever your time threshold was)

**Comment by Izalpaiva** [comment]
Is there also a metric to regulate the maximum size of the ripple event ?

**Comment by edeno** [comment]
You can find all the metrics computed here: https://github.com/Eden-Kramer-Lab/ripple_detection/blob/01c9504b7b93cf1a93bd869cab974a2ccf8258c9/ripple_detection/detectors.py#L343

There is a metric that calculates the max ripple size (in units of standard deviations). You can threshold the dataframe as needed based on that metric.

**Comment by edeno** [comment]
Closed by 2eeeb3934835a1b5587a394c36abcbb3014c5e19
